### ISSUE TITLE
Can someone provide a build release?

### ISSUE THREAD

**Issue by herdlevar** [thockco/qmk#5]
I am having trouble building the project as I don't have the necessary dev environment. Can someone please provide a release build so that others and myself can download that instead of having to build the project? Thanks!

**Comment by mewa** [comment]
Hi @herdlevar, you can download the firmware [here](https://github.com/thockco/qmk/releases/tag/v221015).

I would still recommend that you install [Docker](https://www.docker.com/) if you want to customize the firmware. Once you have it installed you can use [build-conundrum.sh](https://github.com/thockco/qmk/blob/v221015/build-conundrum.sh) script to build the firmware.

Or just use this snippet below:
```bash
docker build -t thock/conundrum .
docker run -v $PWD:/qmk_firmware -v $PWD/.build:/qmk_firmware/.build -it thock/conundrum
```
